networks:
  pw-network:

volumes:
  pw-db-data:

services:
  frontend:
    platform: linux/amd64
    image: ${FRONTEND_IMAGE_NAME}
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_FIREBASE_SIGN_IN_URL: ${REACT_APP_FIREBASE_SIGN_IN_URL}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_WEBSOCKET_URL: ${REACT_APP_WEBSOCKET_URL}
        REACT_APP_BACKEND_BASE_URL: ${REACT_APP_BACKEND_BASE_URL}
        REACT_APP_SETTING_TRADER_URL: ${REACT_APP_SETTING_TRADER_URL}
        REACT_APP_SIGNUP_URL: ${REACT_APP_SIGNUP_URL}
        REACT_APP_SIGNUP_ADMIN_URL: ${REACT_APP_SIGNUP_ADMIN_URL}
        REACT_APP_ADMIN_WALLETS_URL: ${REACT_APP_ADMIN_WALLETS_URL}
        REACT_APP_ADMIN_TRADERS_URL: ${REACT_APP_ADMIN_TRADERS_URL}
        REACT_APP_SETTING_URL: ${REACT_APP_SETTING_URL}
        REACT_APP_ADMIN_ORDERS_URL: ${REACT_APP_ADMIN_ORDERS_URL}
        REACT_APP_TRADER_DATA_RUL: ${REACT_APP_TRADER_DATA_RUL}
        REACT_APP_TRANSFER: ${REACT_APP_TRANSFER}
        REACT_APP_ORDER: ${REACT_APP_ORDER}

    restart: always
    ports:
      - "${DOCKER_HOST_FRONTEND_PORT}:80"
    networks:
      - pw-network
    environment:
      - TZ=Asia/Hong_Kong
  db:
    image: mysql:8.0
    container_name: pw-db
    restart: always
    volumes:
      - pw-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Hong_Kong
    ports:
      - "${DOCKER_HOST_DB_SERVER_PORT}:${DB_SERVER_PORT}"
    networks:
      - pw-network
  backend:
    platform: linux/amd64
    image: ${BACKEND_IMAGE_NAME}
    depends_on:
      - db
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_HOST_BACKEND_PORT}:${BACKEND_SERVER_PORT}"
    environment:
      DB_SERVER_HOST: db
      SERVER_PORT: ${BACKEND_SERVER_PORT}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      ADMIN_SECRET_CODE: ${ADMIN_SECRET_CODE}
      GOOGLE_JWK_SET_URI: ${GOOGLE_JWK_SET_URI}
      TZ: Asia/Hong_Kong
    volumes:
      - ${FIREBASE_SERVICE_ACCOUNT_PATH}:/config/service-account.json:ro
    networks:
      - pw-network