server:
  port: ${BACKEND_SERVER_PORT}

spring:
  application:
    name: bankingCoin
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties.hibernate:
      jdbc.time_zone: Asia/Hong_Kong
      dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${GOOGLE_JWK_SET_URI}
          expiration: 3600000


spring.datasource:
  url: jdbc:mysql://${DB_SERVER_HOST}:${DB_SERVER_PORT}/${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}

spring.jackson.time-zone: Asia/Hong_Kong


google:
  api:
    key: ${GOOGLE_APIREACT_APP_FIREBASE_API_KEY}

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}

admin:
  secret:
    code: ${ADMIN_SECRET_CODE}



